live_config_reload = true

[colors.bright]
black = "#5C5C61"
blue = "#6943FF"
cyan = "#80FCFF"
green = "#3AD900"
magenta = "#FB94FF"
red = "#EC3A37"
white = "#2D2B55"
yellow = "#FAD000"

[colors.cursor]
cursor = "#FAD000"
text = "#1E1E3F"

[colors.normal]
black = "#000000"
blue = "#6943FF"
cyan = "#80FCFF"
green = "#75e44c"
magenta = "#FF2C70"
red = "#EC3A37"
white = "#FFFFFF"
yellow = "#FAD000"

[colors.primary]
background = "#1E1E3F"
foreground = "#E1EFFF"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
